version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - setup_remote_docker
      # Mavenキャッシュ
      - restore_cache:
          keys:
            - maven-{{checksum "pom.xml"}}
            - maven
      - run:
          name: Build and Push to GitHub Packages
          command: |
            docker login ghcr.io -u ${GITHUB_USER} -p ${GITHUB_TOKEN}
            mvn -X -B package docker:build docker:push -Dimage.tag=`date +%Y%m%dT%H%M%S-%3N` --file pom.xml -s ./.circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: 
            maven-{{checksum "pom.xml"}}
          expire: 1d
  
  pull_and_push:
    docker: 
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull Container Image
          command: |
            docker login ghcr.io -u ${GITHUB_USER} -p ${GITHUB_TOKEN}
            docker pull ghcr.io/${GITHUB_USER}/hello-app-spring
            docker image ls
      - run:
          name: Push Image to GCP Artifact Registry
          command: |
            echo ${GCP_KEY_FILE} > ./gcp_key.json
            gcloud auth activate-service-account --key-file=./gcp_key.json
            gcloud auth configure-docker asia-northeast1-docker.pkg.dev
            docker tag ghcr.io/${GITHUB_USER}/hello-app-spring  asia-northeast1-docker.pkg.dev/test-circleci-421201/test-docker/hello-app-spring
            docker push asia-northeast1-docker.pkg.dev/test-circleci-421201/test-docker/hello-app-spring

workflows: 
  sample_workflow:
    jobs:
      - build_and_push
      - pull_and_push