name: image-publish

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: ghcr.io
        settings-path: ${{ github.workspace }}
    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B package docker:build docker:push -Dimage.tag=`date +%Y%m%dT%H%M%S-%3N` --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
      env: # 自分のリポジトリへのアクセスなのでPATではなくGITHUB_TOKENの権限で登録もできる
        GITHUB_TOKEN: ${{ github.token }}

    - name: Setup Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure docker for artifact registry
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev
        
    - name: set TAG
      run: |
        echo "TAG=$(echo $GITHUB_REF | awk -F/ '{print $NF}')" >> $GITHUB_ENV

    - name: Build
      run: |
        docker build -t asia-northeast1-docker.pkg.dev/careful-form-419411/cloud-run-source-deploy/example:${{ env.TAG }} ./    
    
    - name: Push
      run: |
        docker push asia-northeast1-docker.pkg.dev/careful-form-419411/cloud-run-source-deploy/example:${{ env.TAG }}

    - name: Deploy to Cloud Run
      run: |
          gcloud run deploy sample-docker \
            --image asia-northeast1-docker.pkg.dev/careful-form-419411/cloud-run-source-deploy/example:${{ env.TAG }} \
            --port 8080 \
            --region asia-northeast1 \
            --platform=managed \
            --allow-unauthenticated \
            --quiet \
            --set-env-vars=ENV=PRODUCTION
